-- Supabase migration for Organizational Worldviews Annotations
-- Run in Supabase SQL Editor (Dashboard > SQL Editor > New query)

create table if not exists sources (
  id           text primary key,
  display_num  text not null default '',
  author       text not null default '',
  section      text not null default '',
  year         text not null default '',
  data_section text not null default '',
  data_year    text not null default '',
  data_type    text not null default '',
  citation     text not null default '',
  annotation   text not null default '',
  sort_order   integer not null default 0,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

alter table sources enable row level security;
create policy "public read" on sources for select using (true);
create policy "anon insert" on sources for insert with check (true);
create policy "anon update" on sources for update using (true);
create policy "anon delete" on sources for delete using (true);

create or replace function update_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

drop trigger if exists sources_updated_at on sources;
create trigger sources_updated_at
  before update on sources
  for each row execute procedure update_updated_at();

create table if not exists keywords (
  id         uuid primary key default gen_random_uuid(),
  source_id  text references sources(id) on delete cascade,
  keyword    text not null,
  created_at timestamptz default now()
);
alter table keywords enable row level security;
create policy "public read kw" on keywords for select using (true);
create policy "anon insert kw" on keywords for insert with check (true);
create policy "anon delete kw" on keywords for delete using (true);

insert into sources
  (id, display_num, author, section, year, data_section, data_year, data_type, citation, annotation, sort_order)
values
  ('source-1', '01', 'Burrell & Morgan', 'Foundations', '1979', '', '', '', 'Burrell, G., & Morgan, G. (1979). <em>Sociological paradigms and organisational analysis: Elements of the sociology of corporate life</em>. Heinemann Educational Books.', '', 1),
  ('source-2', '02', 'Morgan', 'Foundations', '1997', '', '', '', 'Morgan, G. (1997). <em>Images of organization</em> (2nd ed.). Sage Publications.', '', 2),
  ('source-3', '03', 'DiMaggio & Powell', 'Foundations', '1983', '', '', '', 'DiMaggio, P. J., & Powell, W. W. (1983). The iron cage revisited: Institutional isomorphism and collective rationality in organizational fields. <em>American Sociological Review, 48</em>(2), 147–160. https://doi.org/10.2307/2095101', '', 3),
  ('source-4', '04', 'Tsoukas & Chia', 'Foundations', '2002', '', '', '', 'Tsoukas, H., & Chia, R. (2002). On organizational becoming: Rethinking organizational change. <em>Organization Science, 13</em>(5), 567–582. https://doi.org/10.1287/orsc.13.5.567.7810', '', 4),
  ('source-5', '05', 'Scott & Davis', 'Foundations', '2007', '', '', '', 'Scott, W. R., & Davis, G. F. (2007). <em>Organizations and organizing: Rational, natural, and open system perspectives</em>. Pearson Prentice Hall.', '', 5),
  ('source-57', '06', 'Kuhn', 'Foundations', '1962', '', '', '', 'Kuhn, T. S. (1962). <em>The structure of scientific revolutions</em>. University of Chicago Press.', '', 6),
  ('source-58', '07', 'Mintzberg', 'Foundations', '1979', '', '', '', 'Mintzberg, H. (1979). <em>The structuring of organizations: A synthesis of the research</em>. Prentice Hall.', '', 7),
  ('source-59', '08', 'March & Simon', 'Foundations', '1958', '', '', '', 'March, J. G., & Simon, H. A. (1958). <em>Organizations</em>. Wiley.', '', 8),
  ('source-60', '09', 'Lawrence & Lorsch', 'Foundations', '1967', '', '', '', 'Lawrence, P. R., & Lorsch, J. W. (1967). <em>Organization and environment: Managing differentiation and integration</em>. Harvard Business School Press.', '', 9),
  ('source-6', '10', 'Burns', 'Leadership', '1978', '', '', '', 'Burns, J. M. (1978). <em>Leadership</em>. Harper & Row.', '', 10),
  ('source-7', '11', 'Uhl-Bien', 'Leadership', '2006', '', '', '', 'Uhl-Bien, M. (2006). Relational leadership theory: Exploring the social processes of leadership and organizing. <em>The Leadership Quarterly, 17</em>(6), 654–676. https://doi.org/10.1016/j.leaqua.2006.10.007', '', 11),
  ('source-8', '12', 'Schein', 'Leadership', '2010', '', '', '', 'Schein, E. H. (2010). <em>Organizational culture and leadership</em> (4th ed.). Jossey-Bass.', '', 12),
  ('source-9', '13', 'Avolio & Gardner', 'Leadership', '2005', '', '', '', 'Avolio, B. J., & Gardner, W. L. (2005). Authentic leadership development: Getting to the root of positive forms of leadership. <em>The Leadership Quarterly, 16</em>(3), 315–338. https://doi.org/10.1016/j.leaqua.2005.03.001', '', 13),
  ('source-10', '14', 'House & Gupta', 'Leadership', '2004', '', '', '', 'House, R. J., Hanges, P. J., Javidan, M., Dorfman, P. W., & Gupta, V. (Eds.). (2004). <em>Culture, leadership, and organizations: The GLOBE study of 62 societies</em>. Sage Publications.', '', 14),
  ('source-11', '15', 'Grosser & Moon', 'Leadership', '2019', '', '', '', 'Grosser, K., & Moon, J. (2019). CSR and feminist organization studies: Towards an integrated theorization for the analysis of gender issues. <em>Journal of Business Ethics, 155</em>(2), 321–342. https://doi.org/10.1007/s10551-017-3510-x', '', 15),
  ('source-12', '16', 'Weick', 'Sensemaking', '1995', '', '', '', 'Weick, K. E. (1995). <em>Sensemaking in organizations</em>. Sage Publications.', 'Karl Weick’s work in sensemaking, though emerging as a corrective to overly rigid managerial logic, sits firmly within a human-centered frame. Weick views sensemaking from an action-oriented lens: situations become words, and words become actions. Organizational worlds are brought into existence through categories, labels, and symbolic interpretation—a process that is inherently reductionist. Embodied knowledge, tacit knowledge, and more-than-human signals fall outside this frame. Importantly, Weick highlights that power shapes who gets to define the categories that constitute organizational reality: those with greater access and authority shape how others make sense of their environment, act, and participate. Mainstream management and organizational theory has historically privileged abstract, representational knowledge—metrics, categories, models, indicators, and quantitative data—and Weick’s framework both reflects and reinforces this narrowing tendency. His approach explains how meaning-making influences organizational action, but rarely asks to what end, or who and what are excluded from participation. This source is valuable to my literature review because it illustrates how dominant organizational epistemologies are structured to exclude non-human and non-cognitive forms of knowing. In asking how different organizational worldviews shape leadership values and culture, Weick’s sensemaking framework exemplifies how Western management thought encodes what is legible, who counts as an actor, and what kinds of knowledge are deemed actionable. It provides a critical foil against which relational, posthumanist, and Indigenous frameworks can be assessed.', 16),
  ('source-13', '17', 'Weick & Obstfeld', 'Sensemaking', '2005', '', '', '', 'Weick, K. E., Sutcliffe, K. M., & Obstfeld, D. (2005). Organizing and the process of sensemaking. <em>Organization Science, 16</em>(4), 409–421. https://doi.org/10.1287/orsc.1050.0133', 'Weick, Sutcliffe, and Obstfeld extend sensemaking theory by examining how organizational actors continuously make sense of ambiguous, unfolding situations through retrospective interpretation and coordinated action. This work deepens the argument that organizational worlds are constituted through categories, labels, and symbolic interpretation—a framing that is inherently reductionist. Embodied knowledge, tacit knowledge, and more-than-human signals fall outside this frame. The emphasis on cognitive and linguistic meaning-making reinforces the primacy of human interpretation, even as it acknowledges that meaning is socially negotiated and context-dependent. Mainstream management and organizational theory has historically privileged abstract, representational knowledge—metrics, categories, models, and quantitative data—and this framework narrows what organizations can perceive and the relationships that may emerge with/in ecosystems. Many ecological relationships remain invisible because they resist measurement and visualization or dominant modes of communication. This source serves my literature review by demonstrating how influential sensemaking theories, despite their sophistication, remain tethered to human-centered epistemologies. In the context of my research question—how organizational worldviews shape leadership values, culture, and decision-making—this work helps explain why mechanistic and representational forms of knowledge production remain dominant. Placing this work in dialogue with relational and posthumanist traditions surfaces the onto-epistemological limits of dominant organizational thought.', 17),
  ('source-14', '18', 'Maitlis & Christianson', 'Sensemaking', '2014', '', '', '', 'Maitlis, S., & Christianson, M. (2014). Sensemaking in organizations: Taking stock and moving forward. <em>The Academy of Management Annals, 8</em>(1), 57–125. https://doi.org/10.1080/19416520.2014.873177', '', 18),
  ('source-15', '19', 'Gioia & Chittipeddi', 'Sensemaking', '1991', '', '', '', 'Gioia, D. A., & Chittipeddi, K. (1991). Sensemaking and sensegiving in strategic change initiation. <em>Strategic Management Journal, 12</em>(6), 433–448. https://doi.org/10.1002/smj.4250120604', '', 19),
  ('source-16', '20', 'Orlikowski', 'Practice Theory', '2007', '', '', '', 'Orlikowski, W. J. (2007). Sociomaterial practices: Exploring technology at work. <em>Organization Studies, 28</em>(9), 1435–1448. https://doi.org/10.1177/0170840607081138', '', 20),
  ('source-17', '21', 'Orlikowski & Scott', 'Practice Theory', '2008', '', '', '', 'Orlikowski, W. J., & Scott, S. V. (2008). Sociomateriality: Challenging the separation of technology, work, and organization. <em>The Academy of Management Annals, 2</em>(1), 433–474. https://doi.org/10.1080/19416520802211644', '', 21),
  ('source-18', '22', 'Gherardi', 'Practice Theory', '2016', '', '', '', 'Gherardi, S. (2016). To start practice theorizing anew: The contribution of the concepts of agencement and formativeness. <em>Organization, 23</em>(5), 680–698. https://doi.org/10.1177/1350508415605174', '', 22),
  ('source-19', '23', 'Champenois & Thompson', 'Practice Theory', '2025', '', '', '', 'Champenois, C., Dimov, D., Gherardi, S., Hjorth, D., & Thompson, N. A. (2025). Theorizing the processes and practices of entrepreneuring at work. <em>Human Relations, 78</em>(6), 651–662. https://doi.org/10.1177/00187267251328865', '', 23),
  ('source-20', '24', 'Nicolini', 'Practice Theory', '2012', '', '', '', 'Nicolini, D. (2012). <em>Practice theory, work, and organization: An introduction</em>. Oxford University Press.', '', 24),
  ('source-21', '25', 'Feldman & Orlikowski', 'Practice Theory', '2011', '', '', '', 'Feldman, M. S., & Orlikowski, W. J. (2011). Theorizing practice and practicing theory. <em>Organization Science, 22</em>(5), 1240–1253. https://doi.org/10.1287/orsc.1100.0582', '', 25),
  ('source-51', '26', 'Schatzki', 'Practice Theory', '1996', '', '', '', 'Schatzki, T. R. (1996). <em>Social practices: A Wittgensteinian approach to human activity and the social</em>. Cambridge University Press.', '', 26),
  ('source-52', '27', 'Latour', 'Practice Theory', '2005', '', '', '', 'Latour, B. (2005). <em>Reassembling the social: An introduction to Actor-Network Theory</em>. Oxford University Press.', 'Philosopher Bruno Latour writes that “to limit the discussion to humans, their interests, their subjectivities, and their rights, will appear as strange a few years from now as having denied the right to vote to slaves, poor people or women.” Latour’s provocation does more than call for the ethical inclusion of nonhuman actors; it exposes a deeper ontological failure in how organizational life has been imagined. Latour reveals the limits of frameworks that assume only humans are the ones who get to matter, act, or decide. Through Actor-Network Theory, Latour argues that agency is distributed across configurations of humans, nonhumans, materials, infrastructures, and environments—a proposition that fundamentally destabilizes the human-centered ontology of mainstream management thought. Social life, for Latour, is not a fixed context within which organizations operate, but an ongoing achievement continually assembled and reassembled through heterogeneous networks of actors. This source is foundational to my literature review because it offers one of the most rigorous philosophical challenges to anthropocentric organizational theory. In examining how different organizational worldviews shape leadership values, decision-making, and structure, Latour’s framework insists that any adequate account of organizational life must include the full range of actants—human and nonhuman—whose relations constitute organizational reality. This has direct implications for how leadership, agency, and accountability are understood, making Actor-Network Theory an essential conceptual resource for the relational, ecological organizational theory this research aims to advance.', 27),
  ('source-22', '28', 'de Vaujany & Silva', 'Posthumanism', '2024', '', '', '', 'de Vaujany, F.-X., Gherardi, S., & Silva, P. (Eds.). (2024). <em>Organization studies and posthumanism: Towards a more-than-human world</em>. Routledge. https://doi.org/10.4324/9781032617169', '', 28),
  ('source-23', '29', 'Gherardi & Silva', 'Posthumanism', '2024', '', '', '', 'Gherardi, S., de Vaujany, F.-X., & Silva, P. (2024). General introduction: Too-human? Inquiring in-between different disciplinary areas in managing and organizing. In F.-X. de Vaujany, S. Gherardi, & P. Silva (Eds.), <em>Organization studies and posthumanism</em> (pp. 1–20). Routledge.', '', 29),
  ('source-24', '30', 'Ehrnström-Fuentes & Annala Tesfaye', 'Posthumanism', '2025', '', '', '', 'Ehrnström-Fuentes, M., Böhm, S., Hagolani-Albov, S., & Annala Tesfaye, L. (2025). Multispecies organizing in the web of life: Ethico-political dynamics of matters of care in ecologies-in-place. <em>Business Ethics Quarterly</em>. Advance online publication. https://doi.org/10.1017/beq.2025.8', '', 30),
  ('source-25', '31', 'Wenzel', 'Posthumanism', '2025', '', '', '', 'Wenzel, M. (2025). Organized carelessness: De-ethicizing the organization of death. <em>Business Ethics Quarterly, 35</em>(4), 675–705. https://doi.org/10.1017/beq.2025.10083', '', 31),
  ('source-26', '32', 'Huopalainen & Tallberg', 'Posthumanism', '2026', '', '', '', 'Huopalainen, A., Satama, S., & Tallberg, L. (2026). Aesthetic encounters, canines, and care: New multispecies methodological avenues in organizational and business ethics. <em>Journal of Business Ethics, 203</em>, 241–257. https://doi.org/10.1007/s10551-025-06035-4', '', 32),
  ('source-27', '33', 'Allen & Strauß', 'Posthumanism', '2026', '', '', '', 'Allen, S., & Strauß, A. (2026). Thinking-being with a garden: Developing ecocentric ethics for sustainable organising. <em>Journal of Business Ethics</em>. Advance online publication. https://doi.org/10.1007/s10551-026-06255-2', '', 33),
  ('source-28', '34', 'Barad', 'Posthumanism', '2007', '', '', '', 'Barad, K. (2007). <em>Meeting the universe halfway: Quantum physics and the entanglement of matter and meaning</em>. Duke University Press.', 'Within posthumanist thinking, Barad’s theory of agential realism gives us a new conceptual orientation. For Barad, reality is constituted through intra-action rather than interaction between already formed entities, with matter and meaning coming into being together through material–discursive practices. Organizations, humans, nonhumans, materials, and environments do not first exist and then enter into relationships; rather, they emerge through ongoing processes of co-emergence. The dominant mechanistic worldview is not absent from relations—rather, it organizes them in inconsistent, instrumental, and often unjust ways, privileging extractive and asymmetrical forms of connection. From this relational perspective, organizations cannot be understood as bounded actors operating within external environments; organizational relationships are continually made and unmade as life unfolds. Knowledge is no longer understood as a tool for mastery or control, but as a relational process through which humans, nonhumans, and material arrangements continuously co-emerge. This source is central to my literature review because agential realism fundamentally challenges the mechanistic, bounded-actor model of organizations that undergirds most mainstream management theory. In asking how different organizational worldviews shape leadership values and culture, Barad’s framework surfaces how agency, responsibility, and decision-making are distributed across human and non-human configurations rather than residing solely in individual actors or institutional structures.', 34),
  ('source-29', '35', 'Haraway', 'Posthumanism', '1988', '', '', '', 'Haraway, D. J. (1988). Situated knowledges: The science question in feminism and the privilege of partial perspective. <em>Feminist Studies, 14</em>(3), 575–599. https://doi.org/10.2307/3178066', 'Haraway’s concept of sympoiesis articulates a fundamental shift in how we understand knowledge and organizational life by rejecting the possibility of self-contained systems altogether. She claims that worlds are made through creative, collaborative relationships. In this view, organizations are not connected to living systems; they are continuously making-with them. Haraway extends this ontological insight through her notion of response-ability: the capacity to care and respond within multispecies worlds one is already entangled with. Responsibility is not an abstract moral principle or an optional layer added to organizational decision-making. It emerges from attunement and care to relational entanglements and from recognizing that organizational actions reverberate across ecological and temporal scales. Her work on storytelling for multispecies justice further proposes that organizations might learn to perceive themselves as participants within living systems through narrative practices that honor more-than-human entanglement. This source is foundational to my literature review because it offers conceptual language for rethinking organizations as relational, response-able participants within living systems. Haraway’s framework reframes responsibility as a relational and ecological practice rather than a strategic or compliance-based one. Her notion of making-with directly challenges the extractive and anthropocentric logics encoded in mainstream management thought, positioning organizations as ethically entangled rather than strategically independent.', 35),
  ('source-53', '36', 'Braidotti', 'Posthumanism', '2013', '', '', '', 'Braidotti, R. (2013). <em>The posthuman</em>. Polity Press.', '', 36),
  ('source-54', '37', 'Deleuze & Guattari', 'Posthumanism', '1987', '', '', '', 'Deleuze, G., & Guattari, F. (1987). <em>A thousand plateaus: Capitalism and schizophrenia</em> (B. Massumi, Trans.). University of Minnesota Press.', '', 37),
  ('source-30', '38', 'Oberholzer', 'Indigenous / Decolonial', '2026', '', '', '', 'Oberholzer, S. (2026). Weaving regenerative value through nature-inclusive stakeholder engagement: Insights from Indigenous businesses in the Sierra Nevada. <em>Business & Society</em>. Advance online publication. https://doi.org/10.1177/00076503251407454', '', 38),
  ('source-31', '39', 'Banerjee', 'Indigenous / Decolonial', '2022', '', '', '', 'Banerjee, S. B. (2022). Decolonizing management theory: A critical perspective. <em>Journal of Management Studies, 59</em>(4), 1074–1087. https://doi.org/10.1111/joms.12756', 'Banerjee argues that management knowledge itself is a product of Western epistemologies and colonial histories. Scientific and managerial knowledge relies on categories, classifications, and abstractions that reduce complex relational worlds into controllable units. Techniques of efficiency, productivity, and control—central to scientific management—are not neutral innovations but are historically entangled with extractive systems such as slavery and colonial plantation economies. These logics persist in modern organizations, reproducing racialized, gendered, and geopolitical hierarchies of power. What results is what Banerjee calls epistemic blindness—an inability to perceive certain types of knowledge. This critique extends to contemporary sustainability practices such as ESG and CSR, which frequently reproduce the same extractive and colonial logics through the language of efficiency, measurement, and optimization. This source is important to my literature review because it provides a critical epistemological frame for understanding how organizational worldviews are neither neutral nor universal, but historically shaped by colonial and extractive systems. In examining how different worldviews shape leadership values and organizational culture, Banerjee’s framework foregrounds how dominant management paradigms structurally exclude Indigenous, relational, and more-than-human forms of knowledge—making this source essential for the decolonial turn this research aims to contribute to.', 39),
  ('source-32', '40', 'Banerjee', 'Indigenous / Decolonial', '2003', '', '', '', 'Banerjee, S. B. (2003). Who sustains whose development? Sustainable development and the reinvention of nature. <em>Organization Studies, 24</em>(2), 143–180. https://doi.org/10.1177/0170840603024002341', 'The failure of mechanistic management paradigms becomes visible when placed against the nested polycrises of the present moment: biodiversity loss, climate destabilization, ozone depletion, pollution, soil erosion, and social inequity. These crises are not accidental side effects, but the cumulative result of industrialization and extractive management cultures and their often violent extension into the Global South over the past century. Banerjee challenges dominant assumptions about sustainable development, arguing that it has been largely co-opted by traditional management paradigms and reframed through rational, profit-oriented logics: sustainable development is managed “through ethnocentric, capitalist notions of managerial efficiency that simply reproduce earlier articulations of decentralized capitalism in the guise of sustainable capitalism.” Mechanistic paradigms externalize responsibility, framing ecological harm as an unintended side effect or externality rather than a predictable outcome of extractive organizational design. This source is critical to my literature review for its sustained critique of how management thought reproduces colonial and extractive logics under the guise of sustainability. In examining how organizational worldviews shape leadership values and decision-making, Banerjee (2003) demonstrates how dominant paradigms structurally render ecological and social harm invisible—making it an essential grounding text for arguing that the shift required is not methodological but onto-epistemological.', 40),
  ('source-33', '41', 'Todd', 'Indigenous / Decolonial', '2016', '', '', '', 'Todd, Z. (2016). An Indigenous feminist''s take on the ontological turn: ''Ontology'' is just another word for colonialism. <em>Journal of Historical Sociology, 29</em>(1), 4–22. https://doi.org/10.1111/johs.12124', 'Todd cautions that Western engagements with relationality often reproduce colonial extraction when relationships are abstracted from responsibility. Relationality without accountability, she argues, is violent. Knowledge, governance, and organizational practice must therefore be rooted in reciprocal obligations to land, water, animals, and community. Todd critiques the tendency within Western academic discourse—including the ontological turn in social science—to adopt relational and ecological language without adequately crediting the Indigenous thinkers and traditions from which these insights emerge. This raises urgent questions about how organizations and scholars engage with relational frameworks: whose voices are amplified, whose stories are silenced, and whose responsibilities are rendered invisible? This source is essential to my literature review because it holds relational organizational theory accountable to the political and colonial contexts in which it operates. In asking how different organizational worldviews shape leadership values and culture, Todd’s framework insists that relationality is not merely an epistemological stance but an ethical and political commitment grounded in specific places, histories, and obligations. Todd warns that shifts toward ecological participation must be accompanied by genuine accountability rather than symbolic adoption of Indigenous language.', 41),
  ('source-34', '42', 'Smith', 'Indigenous / Decolonial', '2012', '', '', '', 'Smith, L. T. (2012). <em>Decolonizing methodologies: Research and Indigenous peoples</em> (2nd ed.). Zed Books.', '', 42),
  ('source-35', '43', 'Tuck & Yang', 'Indigenous / Decolonial', '2012', '', '', '', 'Tuck, E., & Yang, K. W. (2012). Decolonization is not a metaphor. <em>Decolonization: Indigeneity, Education & Society, 1</em>(1), 1–40.', '', 43),
  ('source-55', '44', 'Mignolo', 'Indigenous / Decolonial', '2011', '', '', '', 'Mignolo, W. D. (2011). <em>The darker side of western modernity: Global futures, decolonial options</em>. Duke University Press. https://doi.org/10.1215/9780822394501', '', 44),
  ('source-36', '45', 'Whiteman & Cooper', 'Ecological', '2000', '', '', '', 'Whiteman, G., & Cooper, W. H. (2000). Ecological embeddedness. <em>Academy of Management Journal, 43</em>(6), 1265–1282. https://doi.org/10.2307/1556349', 'Whiteman and Cooper frame the role of organizations as ecologically embedded and place-sourced. Sustainability, in their view, is insufficient if it merely slows degradation—organizations must actively participate in restoring the conditions that allow life to flourish through respect and reciprocity. Through their study of Cree hunters and tallymen in the subarctic, Whiteman and Cooper demonstrate how genuine ecological embeddedness involves intimate, reciprocal knowledge of and accountability to specific places, species, and seasonal cycles—a form of organizational knowing that conventional management frameworks cannot accommodate. Their work surfaces how place-based and Indigenous ecological relationships challenge the abstract, decontextualized models of sustainability that dominate mainstream organizational discourse. This text is important because it brings forth the principle of ecological embeddedness and its contribution to sustainability in management contexts. This source is valuable to my literature review because it provides an empirically grounded account of what ecologically embedded organizing actually looks like in practice. In examining how organizational worldviews shape leadership values and decision-making, Whiteman and Cooper demonstrate that ecological orientation is not a strategic add-on but a fundamental ontological commitment to place and reciprocity. Research is needed on how organizations might cultivate this kind of embeddedness—through what practices and relational commitments this capacity might emerge.', 45),
  ('source-37', '46', 'Capra', 'Ecological', '1996', '', '', '', 'Capra, F. (1996). <em>The web of life: A new scientific understanding of living systems</em>. Anchor Books.', 'Capra, a pioneer in systems thinking and complexity science, describes living systems as patterns of nested relationships at different scales whose health and meaning cannot be understood by looking at individual parts themselves. He argues that meaning arises from the relationships themselves, and that the whole is more than the sum of its parts. Capra charts a progression from rational, linear, and mechanistic thinking toward synthetic, holistic, and relational thinking, and from values grounded in competition and domination toward those grounded in partnership and ecocentrism. Systems thinking holds that relationships—not individual components—are what make a system intelligible and resilient. The old mechanistic view treated organizations and environments as separable; Capra insists that a system cannot be understood through analysis alone—thinking must be contextual, not merely analytical. This source is foundational to my literature review because it offers a comprehensive framework for understanding organizations as living systems embedded in nested ecological relationships rather than as bounded machines. In examining how organizational worldviews shape leadership values and culture, Capra’s web of life offers a coherent alternative ontology—one oriented toward ecological embeddedness, relational meaning-making, and values of partnership and care rather than optimization and extraction.', 46),
  ('source-38', '47', 'Ingold', 'Ecological', '2000', '', '', '', 'Ingold, T. (2000). <em>The perception of the environment: Essays on livelihood, dwelling and skill</em>. Routledge.', 'Ingold’s dwelling perspective emphasizes that knowledge emerges through movement, attention, and material engagement across multiple senses. Landscapes are not passive settings for organizational action but active teachers. Rather than understanding knowledge as representational—something stored in minds or databases—Ingold frames knowing as a skilled, embodied process of attunement to a living environment. Forests communicate through scent, humidity, sound, and vegetal systems; organizational sensing must extend beyond language and cognition into alternative forms of knowing if it is to engage with ecological reality. Ingold insists that organisms, including humans, know their environments through being-in-the-world—through movement, dwelling, and multisensory participation rather than detached observation or strategic analysis. This source is important to my literature review because it grounds epistemological pluralism in an embodied and ecological theory of knowledge. In examining how organizational worldviews shape leadership values and decision-making, Ingold’s framework challenges the cognitive and representational assumptions that undergird mainstream management epistemology. His dwelling perspective opens space for organizational learning that is place-based, sensory, and relational—forms of knowing that remain invisible within mechanistic paradigms. This is particularly relevant to my proposed research into how arts-based, sound, and listening practices might cultivate relational responsiveness in organizational leadership.', 47),
  ('source-39', '48', 'Meadows', 'Ecological', '2008', '', '', '', 'Meadows, D. H. (2008). <em>Thinking in systems: A primer</em> (D. Wright, Ed.). Chelsea Green Publishing.', 'Meadows emphasizes that meaningful transformation arises not from technical interventions, but from shifts in underlying assumptions and ways of seeing. She approaches systems not as mechanisms to be optimized, but as living processes with emergent properties, feedback loops, and leverage points that can only be perceived through sustained attention and relational awareness. Meadows argues that the most powerful leverage points for change lie not in parameters or rules, but in the paradigms—the shared assumptions and worldviews—that give rise to a system’s goals and structures. Conventional organizational management, with its emphasis on performance monitoring and optimization, tends to target lower-order leverage points while leaving the underlying worldview intact. It is not a practice of optimizing systems and their parts, but rather an invitation to awareness of how systems behave and where transformative leverage lies. This source is important to my literature review because it offers a systems-level argument for why organizational worldviews, rather than operational strategies, are the most consequential drivers of organizational culture and decision-making. In examining how different worldviews shape leadership values and structure, Meadows demonstrates that the deepest leverage for organizational transformation lies in paradigm change—a shift in the assumptions through which organizations understand their purpose, relationships, and obligations.', 48),
  ('source-40', '49', 'Reed', 'Ecological', '2007', '', '', '', 'Reed, B. (2007). Shifting from ''sustainability'' to regeneration. <em>Building Research & Information, 35</em>(6), 674–680. https://doi.org/10.1080/09613210701475753', '', 49),
  ('source-56', '50', 'Bateson', 'Ecological', '1972', '', '', '', 'Bateson, G. (1972). <em>Steps to an ecology of mind: Collected essays in anthropology, psychiatry, evolution, and epistemology</em>. University of Chicago Press.', '', 50),
  ('source-41', '51', 'Plumwood', 'Care Ethics', '1993', '', '', '', 'Plumwood, V. (1993). <em>Feminism and the mastery of nature</em>. Routledge.', '', 51),
  ('source-42', '52', 'Tronto', 'Care Ethics', '1993', '', '', '', 'Tronto, J. C. (1993). <em>Moral boundaries: A political argument for an ethic of care</em>. Routledge.', '', 52),
  ('source-43', '53', 'Held', 'Care Ethics', '2006', '', '', '', 'Held, V. (2006). <em>The ethics of care: Personal, political, and global</em>. Oxford University Press.', '', 53),
  ('source-44', '54', 'Karakilic & Painter', 'Care Ethics', '2022', '', '', '', 'Karakilic, E., & Painter, M. (2022). The (un)surprising nature of creativity: A Deleuzian perspective on the temporality of the creative process. <em>Ephemera: Theory and Politics in Organization, 22</em>(2), 281–308.', '', 54),
  ('source-45', '55', 'Carollo & Shymko', 'Care Ethics', '2025', '', '', '', 'Carollo, L., Sferrazzo, R., & Shymko, Y. (2025). Is it the end of the world as we know it? Apocalyptic reflexivity in and around organizations. <em>Ephemera: Theory and Politics in Organization, 25</em>(1).', '', 55),
  ('source-46', '56', 'Laloux', 'Grey Literature', '2014', '', '', '', 'Laloux, F. (2014). <em>Reinventing organizations: A guide to creating organizations inspired by the next stage of human consciousness</em>. Nelson Parker.', '', 56),
  ('source-47', '57', 'Wheatley', 'Grey Literature', '1992', '', '', '', 'Wheatley, M. J. (1992). <em>Leadership and the new science: Learning about organization from an orderly universe</em>. Berrett-Koehler Publishers.', '', 57),
  ('source-48', '58', 'Senge', 'Grey Literature', '1990', '', '', '', 'Senge, P. M. (1990). <em>The fifth discipline: The art and practice of the learning organization</em>. Currency Doubleday.', '', 58),
  ('source-49', '59', 'Greenleaf', 'Grey Literature', '1977', '', '', '', 'Greenleaf, R. K. (1977). <em>Servant leadership: A journey into the nature of legitimate power and greatness</em>. Paulist Press.', '', 59),
  ('source-50', '60', 'Wahl', 'Grey Literature', '2016', '', '', '', 'Wahl, D. C. (2016). <em>Designing regenerative cultures</em>. Triarchy Press.', 'Wahl argues for a regenerative culture grounded in local, place-based practices and an emphasis on long-term ecological resilience rather than short-term economic gain. Sustainability, in his view, is insufficient if it merely slows degradation; organizations must actively participate in restoring the conditions that allow life to flourish through respect and reciprocity. Wahl frames the role of organizations as ecologically embedded and place-sourced, calling for a fundamental reorientation of design, leadership, and culture toward the health of living systems. He draws on systems thinking, biomimicry, and Indigenous ecological knowledge to argue that regenerative cultures are not a future aspiration but an ecological necessity—rooted in practices that attune organizations to the rhythms, cycles, and relationships of the ecosystems they inhabit. This source is important to my literature review because it translates the onto-epistemological shift toward ecological embeddedness into concrete organizational and cultural terms. In examining how different organizational worldviews shape leadership values and structure, Wahl provides a practitioner-facing account of what it might look like for organizations to genuinely reorient their culture, decision-making, and design around ecological health and regenerative relationships. This makes it a valuable bridge between the philosophical and critical sources in my bibliography and the practical question of how organizational culture can be transformed in ways that sustain life rather than deplete it.', 60);